set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]

set_property PACKAGE_PIN A18 [get_ports UART_TX_0]
set_property PACKAGE_PIN B15 [get_ports UART_RX_1]
set_property PACKAGE_PIN B16 [get_ports UART_TX_1]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX_0]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX_1]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX_0]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX_1]
